version: '3.9'
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db_django1'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./container/db_django1:/var/lib/mysql
  redis:
    image: redis
    restart: always
  pythonproject:
    restart: always
    build:
      context: .
    ports:
      - '8000:8000'
    depends_on:
      - db
    command:
      [ 'python3', './container/manage.py', 'runserver', '0.0.0.0:8000' ]
  worker:
    restart: always
    build:
      context: .
    command: ['celery', '--workdir=./container', '-A', 'container', 'worker']
  celery-beats:
    restart: always
    build:
      context: .
    command: ['celery', '--workdir=./container', '-A', 'container', 'beat']
