# Generated by Django 4.0.5 on 2022-06-10 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название новости')),
                ('content_url', models.URLField(default=None, verbose_name='Ссылка на новость')),
                ('preview_text', models.CharField(default=None, max_length=500, verbose_name='Краткий текст новости')),
                ('full_text', models.TextField(default=None, verbose_name='Текст новости')),
                ('text_autor', models.CharField(default=None, max_length=50, verbose_name='Автор текста')),
                ('published_at', models.DateTimeField(default=None, verbose_name='Дата публикации')),
                ('photo_url', models.URLField(default=None, verbose_name='Ссылка на фото')),
                ('photo_src_name', models.CharField(default=None, max_length=50, verbose_name='Источник фото')),
                ('views', models.PositiveIntegerField(default=None, verbose_name='Просмотры')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agregator.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['title'],
            },
        ),
    ]
