# Generated by Django 4.0.5 on 2022-06-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0002_tag_news_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.TimeField(default=None, verbose_name='Дата публикации'),
        ),
    ]
