# Generated by Django 4.0.5 on 2022-06-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0003_alter_news_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
    ]
