# Generated by Django 4.0.5 on 2022-06-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0004_remove_news_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='preview_text',
        ),
    ]
