# Generated by Django 4.0.5 on 2022-06-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0006_alter_news_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo_url',
            field=models.URLField(default=None, verbose_name='Ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(default=None, verbose_name='Дата публикации'),
        ),
    ]
