# Generated by Django 4.0.5 on 2022-06-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0007_alter_news_photo_url_alter_news_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(to='agregator.tag'),
        ),
    ]
