# Generated by Django 4.0.5 on 2022-06-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0009_remove_news_tags_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagarticle', models.CharField(max_length=50, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['tagarticle'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(to='agregator.tag'),
        ),
    ]
