# Generated by Django 4.0.5 on 2022-06-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0010_tag_news_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagarticle',
            field=models.CharField(choices=[('ukraine', 'Украина'), ('world', 'мир')], max_length=50, verbose_name='Тег'),
        ),
    ]
