# Generated by Django 4.0.5 on 2022-06-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0011_alter_tag_tagarticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
