# Generated by Django 4.0.5 on 2022-06-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0012_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['pk'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
