# Generated by Django 4.0.5 on 2022-11-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0014_news_preview_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='text_autor',
        ),
        migrations.AddField(
            model_name='news',
            name='text_author',
            field=models.CharField(default=None, max_length=50, verbose_name='Автор текста'),
        ),
    ]
