# Generated by Django 4.0.5 on 2022-12-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0018_alter_news_photo_src_name_alter_news_text_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagarticle',
            field=models.CharField(max_length=100, verbose_name='Тег'),
        ),
    ]
